config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'pages#home'

  resources :peptide_proteins

  get '/pages/home', to: 'pages#home'
  get '/pages/view_edit_data', to: 'pages#view_edit_data'
  get '/pages/data_options', to: 'pages#data_options'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/proteins/select_file', to: 'proteins#select_file'
  get '/peptide_sources/select', to: 'peptide_sources#select'
  get '/peptide_sources/select_file_to_parse', to: 'peptide_sources#select_file_to_parse'
  post '/peptide_sources/extract_peptides_from_source', to: 'peptide_sources#extract_peptides_from_source'
  get '/proteins/confirm_delete_all', to: 'proteins#confirm_delete_all'
  get '/peptides/confirm_delete_all', to: 'peptides#confirm_delete_all'
  post '/proteins/upload', to: 'proteins#upload'
  post '/proteins/delete_all', to: 'proteins#delete_all'
  post '/proteins/select_file', to: 'proteins#select_file'
  post '/peptide_proteins/matcher', to: 'peptide_proteins#matcher'

  resources :proteins #, only: [:get, :show]

  root to: 'static_pages#home'

  get '/peptides/select_peptide_file', to: 'peptides#select_peptide_file'
  post '/peptides/load', to: 'peptides#select_peptide_file'
  post '/peptides/upload', to: 'peptides#upload'
  post '/peptides/read_file', to: 'peptides#read_file'
  post '/peptides/delete_all', to: 'peptides#delete_all'
  post '/peptides/find_proteins', to: 'peptides#find_proteins'
  resources :peptides

  post '/peptide_protein/parsimony', to: 'peptide_proteins#parsimony'
  resources :peptide_proteins

  resources :peptide_sources

end

__END__
UB5::Application.routes.draw do

  resources :peptide_proteins

  get "static_pages/home", :as => 'welcome_page'

  get "static_pages/help"

  get "static_pages/data_options"

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/proteins/select_file', to: 'proteins#select_file'
  post '/proteins/upload', to: 'proteins#upload'
  post '/proteins/delete_all', to: 'proteins#delete_all'
  resources :proteins #, only: [:get, :show]

  root to:'static_pages#home'

  get '/peptides/select_peptide_file', to: 'peptides#select_peptide_file'
  post '/peptides/load', to: 'peptides#select_peptide_file'
  post '/peptides/upload', to: 'peptides#upload'
  post '/peptides/read_file', to: 'peptides#read_file'
  post '/peptides/delete_all', to: 'peptides#delete_all'
  post '/peptides/find_proteins', to: 'peptides#find_proteins'
  resources :peptides

  post '/peptide_protein/parsimony', to: 'peptide_proteins#parsimony'
  resources :peptide_proteins

  resources :peptide_sources
  post '/peptide_sources/new_protein_file', to: 'peptide_sources#new_protein_file'

end

app/models/peptide_protein.rb
class PeptideProtein < ActiveRecord::Base
  attr_accessible :peptide_id, :protein_id, :protein_mod_site

  belongs_to :protein
  belongs_to :peptide

  validates :peptide_id, :presence => true
  validates :protein_id, :presence => true
  validates :protein_mod_site, :presence => true

end

app/controllers/peptide_proteins_controller.rb
class PeptideProteinsController < ApplicationController

  def parsimony
    render :parsimony
  end

  # POST matcher
  def matcher
    @total_found = 0
    Peptide.all.each do |pep|
      @total_found += pep.find_my_proteins
    end

  end

  # GET /peptide_proteins
  # GET /peptide_proteins.json
  def index
    @peptide_proteins = PeptideProtein.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @peptide_proteins }
    end
  end

  # GET /peptide_proteins/1
  # GET /peptide_proteins/1.json
  def show
    @peptide_protein = PeptideProtein.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @peptide_protein }
    end
  end

  # GET /peptide_proteins/new
  # GET /peptide_proteins/new.json
  def new
    @peptide_protein = PeptideProtein.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @peptide_protein }
    end
  end

  # GET /peptide_proteins/1/edit
  def edit
    @peptide_protein = PeptideProtein.find(params[:id])
  end

  # POST /peptide_proteins
  # POST /peptide_proteins.json
  def create
    @peptide_protein = PeptideProtein.new(params[:peptide_protein])

    respond_to do |format|
      if @peptide_protein.save
        format.html { redirect_to @peptide_protein, notice: 'Peptide protein was successfully created.' }
        format.json { render json: @peptide_protein, status: :created, location: @peptide_protein }
      else
        format.html { render action: "new" }
        format.json { render json: @peptide_protein.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /peptide_proteins/1
  # PUT /peptide_proteins/1.json
  def update
    @peptide_protein = PeptideProtein.find(params[:id])

    respond_to do |format|
      if @peptide_protein.update_attributes(params[:peptide_protein])
        format.html { redirect_to @peptide_protein, notice: 'Peptide protein was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @peptide_protein.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peptide_proteins/1
  # DELETE /peptide_proteins/1.json
  def destroy
    @peptide_protein = PeptideProtein.find(params[:id])
    @peptide_protein.destroy

    respond_to do |format|
      format.html { redirect_to peptide_proteins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/peptide_proteins_helper.rb
module PeptideProteinsHelper
end

app/views/peptide_proteins/_form.html.erb
<%= form_for(@peptide_protein) do |f| %>
  <% if @peptide_protein.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peptide_protein.errors.count, "error") %> prohibited this peptide_protein from being saved:</h2>

      <ul>
      <% @peptide_protein.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :peptide_id %><br />
    <%= f.number_field :peptide_id %>
  </div>
  <div class="field">
    <%= f.label :protein_id %><br />
    <%= f.number_field :protein_id %>
  </div>
  <div class="field">
    <%= f.label :protein_mod_site %><br />
    <%= f.number_field :protein_mod_site %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peptide_proteins/edit.html.erb
<h1>Editing peptide_protein</h1>

<%= render 'form' %>

<%= link_to 'Show', @peptide_protein %> |
<%= link_to 'Back', peptide_proteins_path %>

app/views/peptide_proteins/index.html.erb
<h1>Listing peptide_proteins</h1>

<table>
  <tr>
    <th>Peptide</th>
    <th>Protein</th>
    <th>Protein mod site</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @peptide_proteins.each do |peptide_protein| %>
  <tr>
    <td><%= peptide_protein.peptide_id %></td>
    <td><%= peptide_protein.protein_id %></td>
    <td><%= peptide_protein.protein_mod_site %></td>
    <td><%= link_to 'Show', peptide_protein %></td>
    <td><%= link_to 'Edit', edit_peptide_protein_path(peptide_protein) %></td>
    <td><%= link_to 'Destroy', peptide_protein, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Peptide protein', new_peptide_protein_path %>

app/views/peptide_proteins/matcher.html.erb
Found <%=@total_found%> matches.

app/views/peptide_proteins/new.html.erb
<h1>New peptide_protein</h1>

<%= render 'form' %>

<%= link_to 'Back', peptide_proteins_path %>

app/views/peptide_proteins/parsimony.html.erb
Parsimony

app/views/peptide_proteins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Peptide:</b>
  <%= @peptide_protein.peptide_id %>
</p>

<p>
  <b>Protein:</b>
  <%= @peptide_protein.protein_id %>
</p>

<p>
  <b>Protein mod site:</b>
  <%= @peptide_protein.protein_mod_site %>
</p>


<%= link_to 'Edit', edit_peptide_protein_path(@peptide_protein) %> |
<%= link_to 'Back', peptide_proteins_path %>