config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'pages#home'

  resources :peptide_proteins

  get '/pages/home', to: 'pages#home'
  get '/pages/view_edit_data', to: 'pages#view_edit_data'
  get '/pages/data_options', to: 'pages#data_options'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/proteins/select_file', to: 'proteins#select_file'
  get '/peptide_sources/select', to: 'peptide_sources#select'
  get '/peptide_sources/select_file_to_parse', to: 'peptide_sources#select_file_to_parse'
  post '/peptide_sources/extract_peptides_from_source', to: 'peptide_sources#extract_peptides_from_source'
  get '/proteins/confirm_delete_all', to: 'proteins#confirm_delete_all'
  get '/peptides/confirm_delete_all', to: 'peptides#confirm_delete_all'
  post '/proteins/upload', to: 'proteins#upload'
  post '/proteins/delete_all', to: 'proteins#delete_all'
  post '/proteins/select_file', to: 'proteins#select_file'
  post '/peptide_proteins/matcher', to: 'peptide_proteins#matcher'

  resources :proteins #, only: [:get, :show]

  root to: 'static_pages#home'

  get '/peptides/select_peptide_file', to: 'peptides#select_peptide_file'
  post '/peptides/load', to: 'peptides#select_peptide_file'
  post '/peptides/upload', to: 'peptides#upload'
  post '/peptides/read_file', to: 'peptides#read_file'
  post '/peptides/delete_all', to: 'peptides#delete_all'
  post '/peptides/find_proteins', to: 'peptides#find_proteins'
  resources :peptides

  post '/peptide_protein/parsimony', to: 'peptide_proteins#parsimony'
  resources :peptide_proteins

  resources :peptide_sources

end

__END__
UB5::Application.routes.draw do

  resources :peptide_proteins

  get "static_pages/home", :as => 'welcome_page'

  get "static_pages/help"

  get "static_pages/data_options"

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/proteins/select_file', to: 'proteins#select_file'
  post '/proteins/upload', to: 'proteins#upload'
  post '/proteins/delete_all', to: 'proteins#delete_all'
  resources :proteins #, only: [:get, :show]

  root to:'static_pages#home'

  get '/peptides/select_peptide_file', to: 'peptides#select_peptide_file'
  post '/peptides/load', to: 'peptides#select_peptide_file'
  post '/peptides/upload', to: 'peptides#upload'
  post '/peptides/read_file', to: 'peptides#read_file'
  post '/peptides/delete_all', to: 'peptides#delete_all'
  post '/peptides/find_proteins', to: 'peptides#find_proteins'
  resources :peptides

  post '/peptide_protein/parsimony', to: 'peptide_proteins#parsimony'
  resources :peptide_proteins

  resources :peptide_sources
  post '/peptide_sources/new_protein_file', to: 'peptide_sources#new_protein_file'

end

app/models/protein.rb
class Protein < ActiveRecord::Base
  attr_accessible :aa_sequence, :accession, :description, :sp_or_tr
  attr_accessor :fasta_file

  has_many :peptide_proteins
  has_many :peptides, through: :peptide_proteins

  validates :sp_or_tr, :presence => true
  validates :accession, :presence => true
  validates :description, :presence => true
  validates :aa_sequence, :presence => true

  def parse_fasta_file(in_fast=nil)   # switch back to class method later?
    in_fast = self.fasta_file if in_fast.nil?
    @protein = Protein.new
    while !in_fast.eof?
      line = in_fast.readline.chomp.strip

      if line[0] == '>'
        # this is the name and info line for one protein
        @protein.save if @protein.valid?   # save the previous protein
        @protein = Protein.new
        info = line.split('|')
        @protein.sp_or_tr = info[0][1..2]     # discard '>' at start
        @protein.accession = info[1]
        @protein.description = info[2]
      else
        # these are some amino acids of the protein
        if @protein.aa_sequence.nil?
          @protein.aa_sequence = line
        else
          @protein.aa_sequence << line
        end

      end   # if line starts with >

    end   # while

    @protein.save if @protein.valid?   # save the final protein

  end     # parse_fasta_file

end

app/controllers/proteins_controller.rb
class ProteinsController < ApplicationController

  def select_file
    render :select_fasta_file
  end

  def read_file
    @peptide_source = PeptideSource.new
    render :read_file
  end

  def confirm_delete_all
    render :confirm_delete_all
  end

  def delete_all
    @protein_count = Protein.count
    Protein.delete_all
    render :delete_proteins
  end

  def upload
    protein = Protein.new
    protein.fasta_file = (params[:fasta_file].tempfile)
    protein.parse_fasta_file()
    @number_of_proteins = Protein.count
    render :upload
  end


  # GET /proteins
  # GET /proteins.json
  def index
    @proteins = Protein.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proteins }
    end
  end

  # GET /proteins/1
  # GET /proteins/1.json
  def show
    @protein = Protein.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @protein }
    end
  end

  # GET /proteins/new
  # GET /proteins/new.json
  def new
    @protein = Protein.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @protein }
    end
  end

  # GET /proteins/1/edit
  def edit
    @protein = Protein.find(params[:id])
  end

  # POST /proteins
  # POST /proteins.json
  def create
    @protein = Protein.new(params[:protein])

    respond_to do |format|
      if @protein.save
        format.html { redirect_to @protein, notice: 'Protein was successfully created.' }
        format.json { render json: @protein, status: :created, location: @protein }
      else
        format.html { render action: "new" }
        format.json { render json: @protein.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proteins/1
  # PUT /proteins/1.json
  def update
    @protein = Protein.find(params[:id])

    respond_to do |format|
      if @protein.update_attributes(params[:protein])
        format.html { redirect_to @protein, notice: 'Protein was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protein.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proteins/1
  # DELETE /proteins/1.json
  def destroy
    @protein = Protein.find(params[:id])
    @protein.destroy

    respond_to do |format|
      format.html { redirect_to proteins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proteins_helper.rb
module ProteinsHelper
end

app/views/proteins/_form.html.erb
<%= form_for(@protein) do |f| %>
  <% if @protein.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@protein.errors.count, "error") %> prohibited this protein from being saved:</h2>

      <ul>
      <% @protein.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sp_or_tr %><br />
    <%= f.text_field :sp_or_tr %>
  </div>
  <div class="field">
    <%= f.label :accession %><br />
    <%= f.text_field :accession %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :aa_sequence %><br />
    <%= f.text_area :aa_sequence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proteins/confirm_delete_all.html.erb
<h1>Are you sure?</h1>
<h2>This will delete all  <%= Protein.count%> <%= "protein".pluralize(Protein.count) %> in the database.</h2>

<%= form_tag({ action: :delete_all, method: 'get' }) do %>
    <%= label_tag :delete_all, '    ' %>
    <%= submit_tag 'Delete all proteins' %>
<% end %>

app/views/proteins/delete_proteins.html.erb
<h1>All <%=@protein_count%> proteins have been deleted from the database</h1>

app/views/proteins/edit.html.erb
<h1>Editing protein</h1>

<%= render 'form' %>

<%= link_to 'Show', @protein %> |
<%= link_to 'Back', proteins_path %>

app/views/proteins/index.html.erb
<h1>Listing proteins</h1>

  <tr>
    <th>Sp or tr</th>
    <th>Accession</th>
    <th>Description</th>
    <th>Aa sequence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proteins.each do |protein| %>
  <tr>
    <td><%= protein.sp_or_tr %></td>
    <td><%= protein.accession %></td>
    <td><%= protein.description %></td>
    <td><%= protein.aa_sequence %></td>
    <td><%= link_to 'Show', protein %></td>
    <td><%= link_to 'Edit', edit_protein_path(protein) %></td>
    <td><%= link_to 'Destroy', protein, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Protein', new_protein_path %>

app/views/proteins/new.html.erb
<h1>New protein</h1>

<%= render 'form' %>

<%= link_to 'Back', proteins_path %>

app/views/proteins/select_fasta_file.html.erb
<h1>Load a list of proteins from a file</h1>
<%= form_tag( {action: :upload}, multipart: true ) do %>
    <%= label_tag :fasta_file, 'path to file with fasta data' %> </p>
    <%= file_field_tag :fasta_file %> </p>
    <%= submit_tag 'Upload file' %> </p>
<% end %>

app/views/proteins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sp or tr:</b>
  <%= @protein.sp_or_tr %>
</p>

<p>
  <b>Accession:</b>
  <%= @protein.accession %>
</p>

<p>
  <b>Description:</b>
  <%= @protein.description %>
</p>

<p>
  <b>Aa sequence:</b>
  <%= @protein.aa_sequence %>
</p>


<%= link_to 'Edit', edit_protein_path(@protein) %> |
<%= link_to 'Back', proteins_path %>

app/views/proteins/upload.html.erb
<%= @number_of_proteins.to_s %> proteins now in database