config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'pages#home'

  resources :peptide_proteins

  get '/pages/home', to: 'pages#home'
  get '/pages/view_edit_data', to: 'pages#view_edit_data'
  get '/pages/data_options', to: 'pages#data_options'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/proteins/select_file', to: 'proteins#select_file'
  get '/peptide_sources/select', to: 'peptide_sources#select'
  get '/peptide_sources/select_file_to_parse', to: 'peptide_sources#select_file_to_parse'
  post '/peptide_sources/extract_peptides_from_source', to: 'peptide_sources#extract_peptides_from_source'
  get '/proteins/confirm_delete_all', to: 'proteins#confirm_delete_all'
  get '/peptides/confirm_delete_all', to: 'peptides#confirm_delete_all'
  post '/proteins/upload', to: 'proteins#upload'
  post '/proteins/delete_all', to: 'proteins#delete_all'
  post '/proteins/select_file', to: 'proteins#select_file'
  post '/peptide_proteins/matcher', to: 'peptide_proteins#matcher'

  resources :proteins #, only: [:get, :show]

  root to: 'static_pages#home'

  get '/peptides/select_peptide_file', to: 'peptides#select_peptide_file'
  post '/peptides/load', to: 'peptides#select_peptide_file'
  post '/peptides/upload', to: 'peptides#upload'
  post '/peptides/read_file', to: 'peptides#read_file'
  post '/peptides/delete_all', to: 'peptides#delete_all'
  post '/peptides/find_proteins', to: 'peptides#find_proteins'
  resources :peptides

  post '/peptide_protein/parsimony', to: 'peptide_proteins#parsimony'
  resources :peptide_proteins

  resources :peptide_sources

end

__END__
UB5::Application.routes.draw do

  resources :peptide_proteins

  get "static_pages/home", :as => 'welcome_page'

  get "static_pages/help"

  get "static_pages/data_options"

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/proteins/select_file', to: 'proteins#select_file'
  post '/proteins/upload', to: 'proteins#upload'
  post '/proteins/delete_all', to: 'proteins#delete_all'
  resources :proteins #, only: [:get, :show]

  root to:'static_pages#home'

  get '/peptides/select_peptide_file', to: 'peptides#select_peptide_file'
  post '/peptides/load', to: 'peptides#select_peptide_file'
  post '/peptides/upload', to: 'peptides#upload'
  post '/peptides/read_file', to: 'peptides#read_file'
  post '/peptides/delete_all', to: 'peptides#delete_all'
  post '/peptides/find_proteins', to: 'peptides#find_proteins'
  resources :peptides

  post '/peptide_protein/parsimony', to: 'peptide_proteins#parsimony'
  resources :peptide_proteins

  resources :peptide_sources
  post '/peptide_sources/new_protein_file', to: 'peptide_sources#new_protein_file'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  </br></br>
  <nav>
    <table>
      <tr>
        <td><%= link_to 'View and edit data', pages_view_edit_data_path %></td><td>&nbsp;&nbsp;</td>
        <td><%= link_to 'Process bulk data', pages_data_options_path %></td><td>&nbsp;&nbsp;</td>
      </tr>
    </table>
  </nav>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>